/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aaudioprocessing_AudioProcessingLibrary */

#ifndef _Included_aaudioprocessing_AudioProcessingLibrary
#define _Included_aaudioprocessing_AudioProcessingLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aaudioprocessing_AudioProcessingLibrary
 * Method:    acousticEchoCancellerCreate
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_aaudioprocessing_AudioProcessingLibrary_acousticEchoCancellerCreate
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     aaudioprocessing_AudioProcessingLibrary
 * Method:    acousticEchoCancellerDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_aaudioprocessing_AudioProcessingLibrary_acousticEchoCancellerDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     aaudioprocessing_AudioProcessingLibrary
 * Method:    acousticEchoCancellerRender
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_aaudioprocessing_AudioProcessingLibrary_acousticEchoCancellerRender
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     aaudioprocessing_AudioProcessingLibrary
 * Method:    acousticEchoCancellerCapture
 * Signature: (J[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aaudioprocessing_AudioProcessingLibrary_acousticEchoCancellerCapture
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
