/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aopus_OpusLibrary */

#ifndef _Included_aopus_OpusLibrary
#define _Included_aopus_OpusLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderGetBitrate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_aopus_OpusLibrary_encoderGetBitrate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderSetBitrate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_aopus_OpusLibrary_encoderSetBitrate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderGetQuality
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_aopus_OpusLibrary_encoderGetQuality
  (JNIEnv *, jclass, jlong);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderSetQuality
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_aopus_OpusLibrary_encoderSetQuality
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderCreate
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_aopus_OpusLibrary_encoderCreate
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderActivateFEC
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_aopus_OpusLibrary_encoderActivateFEC
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderDeactivateFEC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_aopus_OpusLibrary_encoderDeactivateFEC
  (JNIEnv *, jclass, jlong);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_aopus_OpusLibrary_encoderDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderEncode
 * Signature: (J[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aopus_OpusLibrary_encoderEncode
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     aopus_OpusLibrary
 * Method:    decoderCreate
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_aopus_OpusLibrary_decoderCreate
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     aopus_OpusLibrary
 * Method:    decoderDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_aopus_OpusLibrary_decoderDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     aopus_OpusLibrary
 * Method:    decoderDecode
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aopus_OpusLibrary_decoderDecode
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     aopus_OpusLibrary
 * Method:    decoderDecode2
 * Signature: (J[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aopus_OpusLibrary_decoderDecode2
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
